SyntaxHighlighter.autoloader(
	'applescript /forumResources/syntaxhighlighter/Scripts/shBrushAppleScript.js',
	'actionscript3 as3 /forumResources/syntaxhighlighter/Scripts/shBrushAS3.js',
	'bash shell sh /forumResources/syntaxhighlighter/Scripts/shBrushBash.js',
	'coldfusion cf /forumResources/syntaxhighlighter/Scripts/shBrushColdFusion.js',
	'cpp c /forumResources/syntaxhighlighter/Scripts/shBrushCpp.js',
	'c# c-sharp csharp /forumResources/syntaxhighlighter/Scripts/shBrushCSharp.js',
	'css /forumResources/syntaxhighlighter/Scripts/shBrushCss.js',
	'delphi pascal pas /forumResources/syntaxhighlighter/Scripts/shBrushDelphi.js',
	'diff patch /forumResources/syntaxhighlighter/Scripts/shBrushDiff.js',
	'erl erlang /forumResources/syntaxhighlighter/Scripts/shBrushErlang.js',
	'groovy /forumResources/syntaxhighlighter/Scripts/shBrushGroovy.js',
	'haxe hx /forumResources/syntaxhighlighter/Scripts/shBrushHaxe.js',
	'java /forumResources/syntaxhighlighter/Scripts/shBrushJava.js',
	'jfx javafx /forumResources/syntaxhighlighter/Scripts/shBrushJavaFX.js',
	'js jscript javascript /forumResources/syntaxhighlighter/Scripts/shBrushJScript.js',
	'perl Perl pl /forumResources/syntaxhighlighter/Scripts/shBrushPerl.js',
	'php /forumResources/syntaxhighlighter/Scripts/shBrushPhp.js',
	'text plain /forumResources/syntaxhighlighter/Scripts/shBrushPlain.js',
	'powershell ps posh /forumResources/syntaxhighlighter/Scripts/shBrushPowerShell.js',
	'py python /forumResources/syntaxhighlighter/Scripts/shBrushPython.js',
	'ruby rails ror rb /forumResources/syntaxhighlighter/Scripts/shBrushRuby.js',
	'sass scss /forumResources/syntaxhighlighter/Scripts/shBrushSass.js',
	'scala /forumResources/syntaxhighlighter/Scripts/shBrushScala.js',
	'sql /forumResources/syntaxhighlighter/Scripts/shBrushSql.js',
	'ts typescript /forumResources/syntaxhighlighter/Scripts/shBrushTypeScript.js',
	'vb vbnet /forumResources/syntaxhighlighter/Scripts/shBrushVb.js',
	'xml xhtml xslt html /forumResources/syntaxhighlighter/Scripts/shBrushXml.js'
);

SyntaxHighlighter.all();
